### ISSUE TITLE
full stacktrace of cytoscape exception

### ISSUE THREAD

**Issue by hadfield** [vital-ai/vital-cytoscape#23]
ava.lang.NullPointerException
at org.cytoscape.view.layout.AbstractLayoutTask.computeCentroid(AbstractLayoutTask.java:210) at org.cytoscape.view.layout.AbstractLayoutTask.run(AbstractLayoutTask.java:153) at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.innerRun(JDialogTaskManager.java:321) at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(JDialogTaskManager.java:350) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) at java.util.concurrent.FutureTask.run(FutureTask.java:262) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException at org.cytoscape.view.layout.AbstractLayoutTask.computeCentroid(AbstractLayoutTask.java:210) at org.cytoscape.view.layout.AbstractLayoutTask.run(AbstractLayoutTask.java:153) at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.innerRun(JDialogTaskManager.java:321) at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(JDialogTaskManager.java:350) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) at java.util.concurrent.FutureTask.run(FutureTask.java:262) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException at org.cytoscape.view.layout.AbstractLayoutTask.computeCentroid(AbstractLayoutTask.java:210) at org.cytoscape.view.layout.AbstractLayoutTask.run(AbstractLayoutTask.java:153) at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.innerRun(JDialogTaskManager.java:321) at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(JDialogTaskManager.java:350) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) at java.util.concurrent.FutureTask.run(FutureTask.java:262) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException at org.cytoscape.view.layout.AbstractLayoutTask.computeCentroid(AbstractLayoutTask.java:210) at org.cytoscape.view.layout.AbstractLayoutTask.run(AbstractLayoutTask.java:153) at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.innerRun(JDialogTaskManager.java:321) at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(JDialogTaskManager.java:350) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) at java.util.concurrent.FutureTask.run(FutureTask.java:262) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException at org.cytoscape.view.layout.AbstractLayoutTask.computeCentroid(AbstractLayoutTask.java:210) at org.cytoscape.view.layout.AbstractLayoutTask.run(AbstractLayoutTask.java:153) at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.innerRun(JDialogTaskManager.java:321) at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(JDialogTaskManager.java:350) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) at java.util.concurrent.FutureTask.run(FutureTask.java:262) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) at java.lang.Thread.run(Thread.java:745)

**Comment by hadfield** [comment]
steps to reproduce on mac yosemite 3.1.1:
if I add nodes to network A; add nodes to B, expand A, expand B, everything works.
if I add nodes to A, expand A. Add nodes to B, expand B, it breaks.
i initially searched for “happy” and was expanding the 6 nodes.

**Comment by hadfield** [comment]
this seems to be more of a cytoscape issue than the plugin issue, but we can continue to try to investigate.
